version: '3.3'
services:
  front_end:
    image: front_end
    container_name: front_end
    ports:
      - '80:80'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/:rw
    links:
      - rest_app
  rest_app:
    image: app
    container_name: rest_app
    ports:
      - '8801:8801'
    links:
      - my_db
  my_db:
    image: mysql:8.0.29
    container_name: mysql_container
    volumes:
      - student_tracker_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5080
      MYSQL_DATABASE: tracker

volumes:
  student_tracker_data:
    external: true

networks:
  default:
    external:
      name: java_app
